.TH TANGLET 6 "April 2021" "Tanglet 1.6.0" "Games Manual"

.SH "NAME"
tanglet \- word finding game

.SH "SYNOPSIS"
.B tanglet
[options]
.RI [ file ]

.SH "DESCRIPTION"
Tanglet is a single player word finding game based on Boggle. The object
of the game is to list as many words as you can before the time runs out.
There are several timer modes that determine how much time you start with,
and if you get extra time when you find a word.
.PP
You can join letters horizontally, vertically, or diagonally in any
direction to make a word, so as long as the letters are next to each other
on the board. However, you can not reuse the same letter cells in a single
word. Also, each word must be at least three letters on a normal board,
and four letters on a large board.

.SH "OPTIONS"
.TP
.BR \-h ", " \-\-help
Displays help on commandline options.
.TP
.B \-\-help-all
Displays help including Qt specific options.
.TP
.BR \-v ", " \-\-version
Displays version information.
.TP
.I file
A game file to play.

.SH "SEE ALSO"
.BR qt5options (7)

.SH "REPORTING BUGS"
Report bugs to
.MT tanglet@bugs.gottcode.org
.ME .

.SH "COPYRIGHT"
Copyright \(co 2009-2021 Graeme Gott
.PP
Free use of this software is granted under the terms of the GNU General
Public License version 3 (GPLv3). There is NO WARRANTY, to the extent
permitted by law.

.SH "AUTHOR"
.MT graeme@gottcode.org
Graeme Gott
.ME .
