.TH "TANGLET" "6" "April 2021" "Games"

.SH "NAME"
tanglet \- word finding game

.SH "SYNOPSIS"
.PP
.B tanglet
[options]
.I [file]

.SH "DESCRIPTION"
.PP
Tanglet is a single player word finding game based on Boggle. The object
of the game is to list as many words as you can before the time runs out.
There are several timer modes that determine how much time you start with,
and if you get extra time when you find a word.
.PP
You can join letters horizontally, vertically, or diagonally in any
direction to make a word, so as long as the letters are next to each other
on the board. However, you can not reuse the same letter cells in a single
word. Also, each word must be at least three letters on a normal board,
and four letters on a large board.

.SH "OPTIONS"
.TP
.BR \-h ", " \-\-help
Displays help on commandline options.
.TP
.B \-\-help-all
Displays help including Qt specific options.
.TP
.BR \-v ", " \-\-version
Displays version information.
.TP
.I file
A game file to play.

.SH "SEE ALSO"
.PP
.BR "qt5options"(7)

.SH "REPORTING BUGS"
.PP
Report bugs to
.MT tanglet@bugs.gottcode.org
.ME .

.SH "COPYRIGHT"
.PP
Copyright \(co 2009-2021 Graeme Gott
.PP
This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 3 of the License, or
(at your option) any later version.
.PP
This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.
.PP
You should have received a copy of the GNU General Public License
along with this program. If not, see
.UR http://www.gnu.org/licenses/
.UE .

.SH "AUTHOR"
.MT graeme@gottcode.org
Graeme Gott
.ME .
